INSERT INTO resource (LEVEL, QUANTITY, CATEGORY, DESCRIPTION, NAME, TYPE) VALUES (1, 1, "RISORSA","COLTELLO","COLTELLO","ARMA");
INSERT INTO resource (LEVEL, QUANTITY, CATEGORY, DESCRIPTION, NAME, TYPE) VALUES (1, 1, "RISORSA","RESTO AEREO","RESTO AEREO","ARMA");
INSERT INTO resource (LEVEL, QUANTITY, CATEGORY, DESCRIPTION, NAME, TYPE) VALUES (2, 2, "RISORSA","ACQUA","ACQUA","CIBO");
INSERT INTO resource (LEVEL, QUANTITY, CATEGORY, DESCRIPTION, NAME, TYPE) VALUES (1, 1, "RISORSA","BACCA","BACCA","CIBO");
