INSERT INTO attack (DAMAGE, NAME, TYPE) VALUES (1,"morso","nemico");
INSERT INTO attack (DAMAGE, NAME, TYPE) VALUES (1,"veleno","nemico");
INSERT INTO attack (DAMAGE, NAME, TYPE) VALUES (3,"affonda","risorsa");
INSERT INTO attack (DAMAGE, NAME, TYPE) VALUES (1,"taglia","risorsa");
INSERT INTO attack (DAMAGE, NAME, TYPE) VALUES (1,"affetta","risorsa");
INSERT INTO event (type, NAME, description, quantity,level)VALUES('NEMICO','Ragno','ragno',1,1);
SET @id := LAST_INSERT_ID();
INSERT INTO enemy (id,HEALTH) VALUES (@id,3);
INSERT INTO event (quantity,level,description,NAME,type) VALUES (1, 1,"serpente","serpente","NEMICO");
SET @id := LAST_INSERT_ID();
INSERT INTO enemy (id,HEALTH) VALUES (@id,3);
INSERT INTO enemy_attack (enemy_id, attacks_id) SELECT e.id, a.id FROM event e, attack a WHERE a.name="morso" AND e.NAME="ragno";
INSERT INTO enemy_attack (enemy_id, attacks_id) SELECT e.id, a.id FROM event e, attack a WHERE a.name="veleno" AND e.NAME="serpente";
INSERT INTO event (level, quantity,description, NAME, type) VALUES (1, 1,"COLTELLO","COLTELLO","RISORSA");
SET @id := LAST_INSERT_ID();
INSERT INTO simple_resource (id,CATEGORY) VALUES (@id, "ARMA");
INSERT INTO event (level, quantity,description, NAME, type) VALUES (1, 1,"RESTO AEREO","RESTO AEREO","RISORSA");
SET @id := LAST_INSERT_ID();
INSERT INTO simple_resource (id, CATEGORY) VALUES (@id, "ARMA");
INSERT INTO event (level, quantity,description, NAME, type) VALUES (2, 2,"ACQUA","ACQUA","RISORSA");
SET @id := LAST_INSERT_ID();
INSERT INTO simple_resource (id, CATEGORY) VALUES (@id, "CIBO");
INSERT INTO event (level, quantity,description, NAME, type) VALUES (1, 1,"BACCA","BACCA","RISORSA");
SET @id := LAST_INSERT_ID();
INSERT INTO simple_resource (id, CATEGORY) VALUES (@id, "CIBO");
INSERT INTO event (level, quantity,description, NAME, type) VALUES (2, 2,"LEGNO","LEGNO","RISORSA");
SET @id := LAST_INSERT_ID();
INSERT INTO simple_resource (id, CATEGORY) VALUES (@id, "COSTRUZIONE");
INSERT INTO event (level, quantity,description, name, type) VALUES (1, 1,"METALLO","METALLO","RISORSA");
SET @id := LAST_INSERT_ID();
INSERT INTO simple_resource (id, CATEGORY) VALUES (@id, "COSTRUZIONE");
INSERT INTO simple_resource_attack (SimpleResource_id, attacks_id) SELECT s.id, a.id FROM simple_resource s JOIN event e ON s.id=e.id JOIN attack a ON a.name = 'taglia' WHERE e.NAME="COLTELLO";
INSERT INTO simple_resource_attack (SimpleResource_id, attacks_id) SELECT s.id, a.id FROM simple_resource s JOIN event e ON s.id=e.id JOIN attack a ON a.name = 'affetta' WHERE e.NAME="RESTO AEREO";
INSERT INTO mode (DESCRIPTION,NUM_RESOURCES,NUM_ENEMY,TOTAL_AREA) VALUES ("Easy",4,2,8);
INSERT INTO mode (DESCRIPTION,NUM_RESOURCES,NUM_ENEMY,TOTAL_AREA) VALUES ("Medium",8,6,18);
INSERT INTO mode (DESCRIPTION,NUM_RESOURCES,NUM_ENEMY,TOTAL_AREA) VALUES ("Hard",12,10,36);
INSERT INTO crafted_resource (LEVEL, QUANTITY, CATEGORY, DESCRIPTION, NAME) VALUES (1, 0, "RISORSA","Legno,Metallo","LANCIA");
INSERT INTO crafted_resource (LEVEL, QUANTITY, CATEGORY, DESCRIPTION, NAME) VALUES (1, 0, "RISORSA","Paglia,Corda,Legno","RIFUGIO");
INSERT INTO craftedResource_components (resource, component) SELECT rc.id, sr.id FROM simple_resource sr JOIN event e ON sr.id=e.id, crafted_resource rc WHERE rc.name="LANCIA" AND e.NAME="LEGNO";
INSERT INTO craftedResource_components (resource, component) SELECT rc.id, sr.id FROM simple_resource sr JOIN event e ON sr.id=e.id, crafted_resource rc WHERE rc.name="LANCIA" AND e.NAME="METALLO";
INSERT INTO crafted_resource_attack (CraftedResource_id, attacks_id) SELECT cr.id, a.id FROM crafted_resource cr, attack a WHERE cr.NAME = "LANCIA" AND a.NAME = "affonda";
INSERT INTO area (NAME,DESCRIPTION) VALUES ("Spiaggia del Relitto","La zona dove sei atterrato. Tra la sabbia e i rottami si trovano oggetti utili… ma anche pericoli nascosti.");
INSERT INTO area (NAME,DESCRIPTION) VALUES ("Foresta densa","Una giungla fitta e umida. È facile perdersi, ma qui si possono trovare piante medicinali e legname.");
INSERT INTO area (NAME,DESCRIPTION) VALUES ("Cascata della Nebbia","Una cascata che cade in una piccola laguna. Acqua potabile e pesci, ma occhio agli animali che si abbeverano.");
INSERT INTO area (NAME,DESCRIPTION) VALUES ("Scogliera dei Corvi","Alte rocce a picco sul mare, con una vista mozzafiato. I venti forti possono essere pericolosi… o utili.");
INSERT INTO area (NAME,DESCRIPTION) VALUES ("Palude Silenziosa","Una zona fangosa e insidiosa. Difficile da attraversare, ma nasconde piante rare e materiali preziosi.");
INSERT INTO area (NAME,DESCRIPTION) VALUES ("Villaggio Abbandonato","Capanni di legno ormai in rovina. Segni di vita passata, forse indizi… o minacce ancora presenti.");
INSERT INTO area (NAME,DESCRIPTION) VALUES ("Caverna dell’Eco","Una grotta profonda che si estende sottoterra. Buona per ripararsi, ma alcuni dicono che non sia vuota.");
INSERT INTO area (NAME,DESCRIPTION) VALUES ("Campo degli Antichi","Un altopiano con strane incisioni su pietre enormi. Un luogo misterioso, forse utile per scoprire qualcosa sull’isola.");
INSERT INTO area (NAME,DESCRIPTION) VALUES ("Spiaggia delle Ossa","Resti di barche e animali lungo la riva. Un posto inquietante, ma pieno di risorse dimenticate");
INSERT INTO area (NAME,DESCRIPTION) VALUES ("Fiume Serpente","Un corso d’acqua che si snoda tra le rocce. Seguirlo può portare a nuove zone, ma occhio ai predatori che lo frequentano");