INSERT INTO resource (LEVEL, QUANTITY, CATEGORY, DESCRIPTION, NAME, TYPE) VALUES (1, 1, "RISORSA","COLTELLO","COLTELLO","ARMA");
INSERT INTO resource (LEVEL, QUANTITY, CATEGORY, DESCRIPTION, NAME, TYPE) VALUES (1, 1, "RISORSA","RESTO AEREO","RESTO AEREO","ARMA");
INSERT INTO resource (LEVEL, QUANTITY, CATEGORY, DESCRIPTION, NAME, TYPE) VALUES (2, 2, "RISORSA","ACQUA","ACQUA","CIBO");
INSERT INTO resource (LEVEL, QUANTITY, CATEGORY, DESCRIPTION, NAME, TYPE) VALUES (1, 1, "RISORSA","BACCA","BACCA","CIBO");
INSERT INTO mode (DESCRIPTION,NUM_RESOURCES,NUM_ENEMY,TOTAL_AREA) VALUES ("Easy",4,0,10);
INSERT INTO mode (DESCRIPTION,NUM_RESOURCES,NUM_ENEMY,TOTAL_AREA) VALUES ("Medium",8,0,18);
INSERT INTO mode (DESCRIPTION,NUM_RESOURCES,NUM_ENEMY,TOTAL_AREA) VALUES ("Hard",12,0,36);